### ISSUE TITLE
Docs could be more specific about how to run Galasa SimBank

### ISSUE THREAD

**Issue by moxeyc** [galasa-dev/galasa.dev#44]
Under Getting Started, in the subtopic 'Launching SimBank' (which might perhaps be named 'Launching Galasa SimBank'), the instructions say _"If you have previously started SimBank, then select and run its run configuration"_.  I wonder if it will be clear to all users how to 'select and run its run configuration'.   Could the docs perhaps explain more about using the Run Configurations menu and selecting the Run Configuration that you created for SimBank?

**Comment by CaroMac** [comment]
Thank you for your comment, we can include updates in the next refresh.

**Comment by hobbit1983** [comment]
Looking at the recent documentation, there is now complete instructions on how to run Galasa:Simbank.  However it is still called simBank - so I will try and fix that now

**Comment by hobbit1983** [comment]
Actually we use simbank all over the show without the galasa prefix.  @moxeyc how worried about that are we?

**Comment by moxeyc** [comment]
I believe we should call it **Galasa:SimBank** (or **Galasa SimBank**) on the first reference on any given page, and also in any headings.   After that, we can be more flexible.  However, we do also need to decide on capitalization and be consistent.  Is it Galasa **sim**Bank or Galasa **Sim**Bank?

**Comment by CaroMac** [comment]
Happy to update the website.We have Galasa Simbank in the TOC so can ensure the first instance on each relevant page says Galasa Simbank if we are happy with that.

**Comment by CaroMac** [comment]
Updates made, will close issue.
