### ISSUE TITLE
Galasa.dev monitoring so we notice when it dies

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/galasa.dev#534]
## Story
As a maintainer of the galasa.dev website, I want to be notified when the code engine instances or load balancers are not active/ facing running issues, so that I can rectify issues before galasa users discover and report them and I can ensure pro-active approaches to maintaining the service.

## Background
IBM Cloud offers some levels of monitoring which are not currently being used to monitor and rectify issues that may arise in hosting the galasa.dev webpage in IBM Cloud.

## Tasks
- [ ] Identify current and potential monitoring available in IBM Cloud
- [ ] Create monitoring and reporting of issues on the galasa-dev slack channel (and possibly email?)

**Comment by hobbit1983** [comment]
Looking at the monitoring available to code engine in IBM cloud it's all a bit heavyweight for what we need.  A simple HTTP get to https://galasa.dev and waiting for a 200 response would probably be more than adequate.  if the check failed then we could drive slack web hook

**Comment by CaroMac** [comment]
completed with Savaas
