### ISSUE TITLE
Front page: better actionability for key features

### ISSUE THREAD

**Issue by ind1go** [galasa-dev/galasa.dev#55]
User testing with new users indicates that the key features on the front page ('Lighten the load', etc) draw in users but then they can take no action based on them.

The text itself interests them, and they wish to click through to to see _how_ they can do X Y and Z, but there's nothing - it becomes a dead end and they have to start the trawl for information from scratch once they get into the About or Docs sections.

**Comment by CaroMac** [comment]
Thank you for the comment. This is planned for a future release.
