### ISSUE TITLE
Wrong test package name in code samples

### ISSUE THREAD

**Issue by banjaxxer** [galasa-dev/galasa.dev#562]
On the [Writing a simbank test page](https://galasa.dev/docs/running-simbank-tests/writing-a-simbank-test) the example code snippets use the incorrect package name **dev.galasa.simbanks.tests;**, it should be _dev.galasa.simbank.tests;_

**Comment by CaroMac** [comment]
Thank you for raising this, will review and correct.

**Comment by CaroMac** [comment]
Eamonn tested out the updated snippet on his machine which worked, no errors

**Comment by techcobweb** [comment]
What's stopping us from closing this item now please? Can we have a list to tick off ?

**Comment by CaroMac** [comment]
published and closed
