### ISSUE TITLE
Docs to include details of gradle building

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/galasa.dev#601]
## Story
As a galasa testcase developer, I want to be able to read how to create a project using the `galasactl` tool, and how you specify the build system you want included, so I can understand the `--maven` and `--gradle` options on that command.

## Background
The ability to build using maven or build using gradle instead is now available.

The `galasactl project create` command now has two new flags `--maven` and `--gradle` to allow the caller to decide which type of build system they want to use when the example is created.
The default is `--maven` if neither are specified. You can use both flags at the same time, resulting in both maven and gradle build files to be created.

To build the generated code using maven: `mvn clean install`

To build the generated code using gradle: `gradle build publishToMavenLocal` 

I suggest we change the example use of `galasactl project create` to include `--maven` and `--gradle` flags to show that we can generate both.

## Tasks
- [ ] Document updates to explain how to use these new flags in galasa.dev in a PR for Caroline to approve or take over as required.

**Comment by CaroMac** [comment]
published 30 Mar
