### ISSUE TITLE
docs: GALASA_BOOTSTRAP not mentioned in the docs.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/galasa.dev#651]
The CLI docs in the readme here: https://github.com/galasa-dev/cli
explain about the GALASA_BOOTSTRAP environment variable.

We need to reflect that in the docs.

eg:

GALASA_BOOTSTRAP

Most commands will need a reference to the Galasa bootstrap file or url. This can be provided with the --bootstrap flag or the GALASA_BOOTSTRAP environment variable. If both are provided, the explicit flag takes precedence.

**Comment by CaroMac** [comment]
Started work on this - raising PR for Eamonn to review

**Comment by CaroMac** [comment]
going out in r 29
