### ISSUE TITLE
Documentation: Using Simbank from the CLI is hard/missing

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/galasa.dev#673]
## Story
As a tester creating galasa tests, when I'm getting started with the CLI, I want to be guided through the install and run the Simbank application, and the install/build/run of the simbank tests using the command-line, so that I get the benefits of simbank but from the CLI.

## Background
The instructions are missing for this.

They should include:
- How to download a binary of the simbank application.
- How to launch the simbank application.
- How to download the simbank tests
- How to build the simbank tests
- How to observe the pom.xml files to extract the values you will need later on to invoke the tests with the CLI
- How to set the CPS properties to the values simbank wants.
- How to set the creds store properties to the values simbank wants.
- How to launch the CLI with all the parameters explicitly spelt-out.

Much of this material is common to the eclipse sections, but some of it isn't

- [x] Testing the instructions work
- [x] Merge

**Comment by techcobweb** [comment]
Raised this story as a result of @Wyvinar and @Akyiaa walking through the oboarding material, and observing where they needed help/guidance.

**Comment by CaroMac** [comment]
Thank you. Will work with @Wyvinar and @Akyiaa to add information

**Comment by techcobweb** [comment]
mike to eye-ball it before merging into main.
