### ISSUE TITLE
Horizontal scrollbar incorrectly appears when browser is maximised

### ISSUE THREAD

**Issue by cxharris** [galasa-dev/galasa.dev#70]
Visit https://galasa.dev/ and maximise your browser.

A horizontal scrollbar (incorrectly) appears - confirmed in Chrome and Firefox.

Edit: Forgot to say that if you gradually reduce the width of the browser window, below a particular width, the scrollbar disappears.

**Comment by ind1go** [comment]
Please add a screenshot.

**Comment by cxharris** [comment]
![horiz-scrollbar](https://user-images.githubusercontent.com/883382/74344263-3a852100-4da4-11ea-8566-47d4f9de0515.png)
