### ISSUE TITLE
Update galasa.dev links

### ISSUE THREAD

**Issue by Wyvinar** [galasa-dev/galasa.dev#729]
# Story
As a galasa user I would like the documentation URLs up to date so I can set my properties correctly

# Background
Whilst going through galasa.dev to look at references to nexus it was noted that a lot of the URLs within galasa-ecosystem-manager.md were out of date to what is currently being used.

**Comment by techcobweb** [comment]
Which URLs ?
Where ?
What should they be in the docs ?
Who is able to list the changes which need to be made please ? 
@Wyvinar

**Comment by techcobweb** [comment]
Closing with the hope that we can re-open it with more detail if @Wyvinar gets the chance...
