### ISSUE TITLE
Clarify use of PCOMM/Galasa

### ISSUE THREAD

**Issue by cxharris** [galasa-dev/galasa.dev#79]
Feedback from SHARE via James.

When reading the doc section on manually exploring SimBank, some users came to the incorrect conclusion that they needed to tie PCOMM up with Galasa in some way. This is not true - PCOMM is used independently to let people play with SImBank but is not needed for Galasa.

Add a note to make this clear.

**Comment by CaroMac** [comment]
have updated the installing section to include a note to clarify this here https://galasa.dev/docs/getting-started/installing
